@hostname = localhost
@port = 7251
@host = https://{{hostname}}:{{port}}
@hotelId = 3
@bookingId = 1
@roomId = 1

### \\\\ HOTEL endpoints ////
    
### Create new hotel
POST {{host}}/api/Hotel
Content-Type: application/json

{
  "name": "Grand Central Hotel",
  "address": "Kyiv, Khreshchatyk St, 1",
  "description": "Luxurious hotel in the heart of the capital with a great view."
}

###
POST {{host}}/api/Hotel
Content-Type: application/json
{
  "name": "Swiss Mountains Luxury Hotel",
  "address": "Swiss Olympic Museum",
  "description": "long description"
}

### Get Hotel by ID
GET {{host}}/api/Hotel/1
Accept: application/json

### Hotel searching (with pagination and sorting)
GET {{host}}/api/Hotel/search?city=Kyiv&searchTerm=Grand&pageNumber=1&pageSize=5&sortBy=name&sortOrder=asc
Accept: application/json

### Get specific Hotel by id
GET {{host}}/api/Hotel/{{hotelId}}
Accept: application/json

### \\\ BOOKING endpoints ////

### Create booking
POST {{host}}/api/Booking
Content-Type: application/json

{
  "userId": 1,
  "roomId": {{roomId}},
  "checkIn": "2026-06-01T14:00:00Z",
  "checkOut": "2026-06-10T11:00:00Z"
}

### Get booking by id 
GET {{host}}/api/Booking/{{bookingId}}
Accept: application/json

### Get data about available hotels in specific dates
@checkIn = 2026-08-01T14:00:00Z
@checkOut = 2026-08-10T11:00:00Z

GET {{host}}/api/Hotel/{{hotelId}}/rooms?checkIn={{checkIn}}&checkOut={{checkOut}}
Accept: application/json